# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Win32-ActAcc
version:      1.1
version_from: ActAcc.pm
installdirs:  site
requires:
    IO::Tee:                       0.64
    Text::Trie:                    
    Win32::OLE:                    0.13

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
